- hosts: localhost
  gather_facts: true
  become: true
  vars:
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains: "{{ lookup('ansible.builtin.file', '/home/' + ansible_user + '/domains.json') | from_json }}"
    certbot_create_extra_args: ""
  roles:
    - ansible-role-certbot
  tasks:
    - name: Run post deploy script
      ansible.builtin.shell: /etc/letsencrypt/renewal-hooks/deploy/certbot-post-deploy.sh
